main/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('shop/', include('shop.urls')),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from shop import views

urlpatterns = [
    path('', views.ProductsListView.as_view(), name='shop'),
    path('cart_view/', views.cart_view, name='cart_view'),
    path('detail/<int:pk>/',views.ProductsDetailView.as_view(), name='shop_detail'),
    path('add-item-to-cart/<int:pk>', views.add_item_to_cart, name='add_item_to_cart'),
    path('delete_item/<int:pk>', views.CartDeleteItem.as_view(), name='cart_delete_item'),
    path('make-order/', views.make_order, name='make_order'),

]

shop/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.db import models, transaction
from django.db.models import Sum
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils import timezone


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование товара')
    code = models.CharField(max_length=255, verbose_name='Код продукта')
    price = models.DecimalField(max_digits=20, decimal_places=2, verbose_name='Цена')
    unit = models.CharField(max_length=255, blank=True, null=True, verbose_name='Единица измерения')
    image_url = models.URLField(blank=True, null=True, verbose_name='url изображения')
    note = models.TextField(blank=True, null=True, verbose_name='записка')
    #data_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['pk']
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'{self.name} - {self.price}'


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True, verbose_name='Cумма')
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True, verbose_name='Комментарий')

    class Meta:
        ordering = ['pk']
        verbose_name_plural = 'Платеж'

    def __str__(self):
        return f'{self.user} - {self.amount}'

    @staticmethod
    def get_balance(user: User):
        amount = Payment.objects.filter(user=user).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class Order(models.Model):
    STATUS_CART = 'Корзина'
    STATUS_WAITING_FOR_PAYMENT = 'Ожидает платежа'
    STATUS_PAID = 'Оплачено'
    STATUS_CHOICES = [
        (STATUS_CART, 'Корзина'),
        (STATUS_WAITING_FOR_PAYMENT, 'Ожидает платежа'),
        (STATUS_PAID, 'Оплачено')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    # items = models.ManyToManyField(OrderItem, related_name='orders')
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=STATUS_CART, verbose_name="Cтатус")
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True, verbose_name="Cумма")
    creation_time = models.DateTimeField(auto_now_add=True)
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, blank=True, null=True, verbose_name='Платеж')
    location = models.CharField(max_length=10, blank=True, verbose_name="Улица")
    home = models.CharField(max_length=50, blank=True, verbose_name="Дом")
    podezd = models.CharField(max_length=20, blank=True, verbose_name="Подъезд")
    etaj = models.CharField(max_length=10, blank=True, verbose_name="Этаж")
    kvartir = models.CharField(max_length=10, blank=True, verbose_name="Квартира/офис")
    domofon = models.CharField(max_length=10, blank=False, verbose_name="Удобный способ оплаты")
    comment = models.TextField(blank=True, null=True, verbose_name='Комментарий')


    class Meta:
        ordering = ['pk']
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'{self.user} - {self.amount}- {self.status}'

    @staticmethod
    def get_cart(user: User):
        cart = Order.objects.filter(user=user,
                                    status=Order.STATUS_CART
                                    ).first()
        if cart and (timezone.now() - cart.creation_time).days > 2:
            cart.delete()
            cart = None

        if not cart:
            cart = Order.objects.create(user=user,
                                        status=Order.STATUS_CART,
                                        amount=0)
        return cart

    def get_amount(self):
        amount = Decimal(0)
        for item in self.orderitem_set.all():
            amount += item.amount
        return amount

    def make_order(self):
        items = self.orderitem_set.all()
        if items and self.status == Order.STATUS_CART:
            self.status = Order.STATUS_WAITING_FOR_PAYMENT
            self.save()
            auto_payment_unpaid_orders(self.user)

    @staticmethod
    def get_amount_of_unpaid_orders(user: User):
        amount = Order.objects.filter(user=user,
                                      status=Order.STATUS_WAITING_FOR_PAYMENT,
                                      ).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
    price = models.DecimalField(max_digits=20, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=0, verbose_name='Скидка')

    class Meta:
        ordering = ['pk']
        verbose_name_plural = 'Элемент заказа'

    def __str__(self):
        return f'{self.product} - {self.price}, руб'

    @property
    def amount(self):
        return self.quantity * (self.price - self.discount)


@transaction.atomic()
def auto_payment_unpaid_orders(user: User):
    unpaid_orders = Order.objects.filter(user=user,
                                         status=Order.STATUS_WAITING_FOR_PAYMENT)
    for order in unpaid_orders:
        if Payment.get_balance(user) < order.amount:
            break
        order.payment = Payment.objects.all().last()
        order.status = Order.STATUS_PAID
        order.save()
        Payment.objects.create(user=user,
                               amount=-order.amount)


@receiver(post_save, sender=OrderItem)
def recalculate_order_amount_after_save(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_delete, sender=OrderItem)
def recalculate_order_amount_after_delete(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_save, sender=Payment)
def auto_payment(sender, instance, **kwargs):
    user = instance.user
    auto_payment_unpaid_orders(user)

shop/forms.py
from django import forms

from shop.models import OrderItem, Order


class AddQuantityForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['quantity']



class OrderUserView(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for visible in self.visible_fields():
    #         visible.field.widget.attrs['class'] = 'form-input'
    class Meta:
         model = Order
         fields = ('location', 'home', 'podezd', 'etaj', 'kvartir', )

shop/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, DeleteView

from shop.forms import AddQuantityForm, OrderUserView
from shop.models import Product, Order, OrderItem

from django.views.generic import TemplateView



class ProductsListView(ListView):
    model = Product #orderitem_set()
    template_name = 'shop/shop.html'


class ProductsDetailView(DetailView):
    model = Product
    template_name = 'shop/shop-details.html'


@login_required(login_url=reverse_lazy('login'))
def add_item_to_cart(request, pk):
    if request.method == 'POST':
        quantity_form = AddQuantityForm(request.POST)
        if quantity_form.is_valid():
            quantity = quantity_form.cleaned_data['quantity']
            if quantity:
                cart = Order.get_cart(request.user)
                # product = Product.objects.get(pk=pk)
                product = get_object_or_404(Product, pk=pk)
                cart.orderitem_set.create(product=product,
                                          quantity=quantity,
                                          price=product.price)
                cart.save()
                return redirect('cart_view')
        else:
            pass
    return redirect('shop')


@login_required(login_url=reverse_lazy('login'))
def cart_view(request):
    cart = Order.get_cart(request.user)
    items = cart.orderitem_set.all()
    context = {
        'cart': cart,
        'items': items,
    }
    return render(request, 'shop/cart.html', context)


@method_decorator(login_required, name='dispatch')
class CartDeleteItem(DeleteView):
    model = OrderItem
    template_name = 'shop/cart.html'
    success_url = reverse_lazy('cart_view')

    # Проверка доступа
    def get_queryset(self):
        qs = super().get_queryset()
        qs.filter(order__user=self.request.user)
        return qs


@login_required(login_url=reverse_lazy('login'))
def make_order(request):
    cart = Order.get_cart(request.user)
    cart.make_order()
    return redirect('shop')

templates/shop/cart.html
{% extends 'base-page.html' %}
{% load static %}

{% block title %}
    Cart
{% endblock title %}

{% block container %}
	<!-- content start -->
	<div class="main-content-wrapper">
		<section class="breadcrumb-section about">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-12 col-lg-5">
						<div class="breadcrumb-wrapper">
							<h2>Корзина</h2>
						</div>
					</div>
				</div>
			</div>
		</section>

		<section class="section">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-12 col-lg-9 ">
						<div class="main-heading-block">
							<h2 class="main-heading">Тележка</h2>
							<!-- <p>EXERCITATIONEM ULLAM CORPORIS</p> -->
						</div>
					</div>
				</div>
                <hr class="hr"/>
				<div class="row" style="font-weight: bold">
					<div class="col-12 col-md-1 item">
                        &nbsp;&nbsp;&nbsp;##
                    </div>
					<div class="col-12 col-md-4 item">
                        Товар
                    </div>
					<div class="col-12 col-md-2 item">
                        Количество
                    </div>
					<div class="col-12 col-md-2 item">
                        Цена за кг
                    </div>
					<div class="col-12 col-md-2 item">
                        Сумма
                    </div>
					<div class="col-12 col-md-1 item">
                        Действие
                    </div>
                </div>
                <hr class="hr"/>

                {% if not items %}
                    <br><br>
                    <div class="row">
                        <div class="col-12 offset-md-6">
                            <h2 style="font-size: large">Пусто</h2>
                        </div>
                    </div>
                    <br><br>
                {% else %}

                    {% for item in items %}
                        <div class="row">
                            <div class="col-12 col-md-1 item">
                                &nbsp;&nbsp;&nbsp;{{ forloop.counter }}
                            </div>
                            <div class="col-12 col-md-4 item">
                                {{ item.product }}
                            </div>
                            <div class="col-12 col-md-2 item">
                                {{ item.quantity }}
                            </div>
                            <div class="col-12 col-md-2 item">
                                {{ item.price }}
                            </div>
                            <div class="col-12 col-md-2 item">
                                {{ item.amount }}
                            </div>
                            <div class="col-12 col-md-1 item">
                                <form method="post" action="{% url 'cart_delete_item' item.pk %}">
                                    {% csrf_token %}
                                    <button type="submit" style="color: blue"><u>удалить</u></button>
                                </form>
                            </div>
                        </div>
                    {% endfor %}

                {% endif %}

                <hr class="hr"/>

				<div class="row" style="font-weight: bold">
                    <div class="col-12 col-md-7 item">
                    </div>
                    <div class="col-12 col-md-2 item">
                         Общая сумма
                    </div>
                    <div class="col-12 col-md-2 item">
                        {{ cart.amount }}
                    </div>
                </div>
<!--                 <hr class="hr"/>
                <div class="row" style="font-weight: bold">
                    <div class="col-12 col-md-7 item">
                    </div>
                    <div class="col-12 col-md-2 item">
                        <div class="row">
                            <div class="col-12 col-lg-4 col-md-4 offset-md-4">
                                <div class="col-12 col-md-1 item">

                                    <input type="text" class="form-input" placeholder="Login"
                                        id="user_form" name="user_form" style="width: 300px;">

                                    <input type="text" class="form-input" placeholder="Login"
                                        id="user_form" name="user_form" style="width: 300px;">

                                                                         
                                </div>
                            </div>
                        </div>
                    </div>
                </div> -->
                <hr class="hr"/>
				<div class="row" style="font-weight: bold">
                    <div class="col-12 col-md-10 item">
                    </div>
                    <div class="col-12 col-md-10 item">
                        <a class="contactus-bar-btn " href="{% url 'shop' %}">Назад</a>
                        <a class="contactus-bar-btn f_right" href="{% url 'make_order' %}">
                            Заказать / Оплатить
                        </a>

                    </div>
                </div>

			</div>
		</section>

	</div>
	<!-- content end -->
{% endblock container %}

templates/shop/index.html
<input type="text" id="inputSearch" placeholder="Search.." title="Type in a category">
 
<ul id="list">
    <li><a href="#">HTML</a></li>
    <li><a href="#">CSS</a></li>
    <li><a href="#">JavaScript</a></li>
    <li><a href="#">PHP</a></li>
    <li><a href="#">Python</a></li>
    <li><a href="#">jQuery</a></li>
    <li><a href="#">SQL</a></li>
    <li><a href="#">Bootstrap</a></li>
    <li><a href="#">Node.js</a></li>
</ul>

templates/shop/shop-details.html
{% extends 'base-page.html' %}
{% load static %}

{% block title %}
    Shopp Details
{% endblock title %}

{% block container %}
	<!-- content start -->
	<div class="main-content-wrapper">
		<section class="breadcrumb-section about">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-12 col-lg-5">
						<div class="breadcrumb-wrapper">
							<h2>Подробнее о продукте</h2>
						</div>
					</div>
				</div>
			</div>
		</section>

		<section class="section">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-12 col-lg-9 ">
						<div class="main-heading-block">
							<h2 class="main-heading">Подробно</h2>
						</div>
					</div>
				</div>
				<div class="row">


					<div class="col-12 col-lg-4 col-md-3 item">
                    </div>
					<div class="col-12 col-lg-4 col-md-6 item">
                        <div class="card" style="width: 18rem;">
                            <img src="{{product.image_url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title"><b>{{ product.name}}</b></h5>
                                <p class="card-text">
                                    {{ product.description }}
                                </p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Цена за кг: {{ product.price }} руб</li>
                                <li class="list-group-item">Описание: {{ product.note }}</li>
                            </ul>
                            <div class="card-body">
                                <a class="learn-more-btn" href="#">В корзину</a>
                                <a class="contactus-bar-btn f_right" href="{% url 'shop' %}">Назад</a>
                            </div>
                        </div>
                    </div>


				</div>
			</div>
		</section>
	</div>
	<!-- content end -->
{% endblock container %}

templates/shop/shop.html
{% extends 'base-page.html' %}
{% load static %}

{% block title %}
    Shop
{% endblock title %}

{% block container %}
 	<div class="main-content-wrapper">
		<div class="breadcrumb-section about">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-12 col-lg-5">
						<div class="breadcrumb-wrapper">
							<h2>Наш магазин</h2>
						</div>
					</div>
				</div>
			</div>
		</div> 

		<div class="section">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-12 col-lg-9 ">
						<div class="main-heading-block">
							<h2 class="main-heading">ЛУЧШИЕ ПРЕДЛОЖЕНИЯ</h2>
							<!-- <p>EXERCITATIONEM ULLAM CORPORIS</p> -->
						</div>
					</div>
				</div>
				<div>
					<label class="ddd">Виды мяса</label>
				</div>
				<div class="form-group">
			        <select class="inputSearch1"  id ="product_search" >			        
			          <option></option>
			          <option>Легкие</option>
			          <option>Грудинка</option>
			          <option>Мякоть задковая</option>
			          <option>Обрезка говяжья</option>
			        </select>
			    </div>
				<input type="text" class ="inputSearch" id="product_search" placeholder="Поиск..." />
				<br></br>
				<div class="row">
                    {% for product in object_list %}
					<section id="{{ product.name}}" class="col-12 col-lg-4 col-md-6 item">
                        <div class="card" style="width: 18rem;">
                            <form method="post" action="{% url 'add_item_to_cart' product.pk %}">
                                <img src="{{product.image_url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title"><b>{{ product.name}}</b></h5>
                                    <p class="card-text">
                                        {{ product.description }}
                                    </p>
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">Цена за кг: {{ product.price }} руб</li>
                                    <li class="list-group-item">
										{% csrf_token %}
										<label class="form-label" for="id_quantity">Количество:</label>
										<input type="number" name="quantity" value="1" min="1"
											   required id="id_quantity"/>
                                    </li>
                                </ul>
                                <div class="card-body">
                                    <button class="learn-more-btn" type="submit">В корзину</button>
                                    <a class="contactus-bar-btn f_right" href="{% url 'shop_detail' product.pk %}">Подробно</a>
                                    <br><br>
                                </div>
                            </form>
                        </div>
                    </section>               
                {% endfor %}
				</div>
			</div>
		</div>
	</div>
	<!-- content end -->
{% endblock container %}